apiVersion: v1
kind: Namespace
metadata:
  name: buildit-jenkins 
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: buildit-jenkins
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: buildit-jenkins
subjects:
- kind: ServiceAccount
  name: default
  namespace: buildit-jenkins
roleRef:
  kind: ClusterRole
  name: buildit-jenkins 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: buildit-jenkins
  namespace: buildit-jenkins
spec:
  ports:
  - name: ui
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: jnlp
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: jenkins
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildit-jenkins-config
  namespace: buildit-jenkins
data:
  JENKINS_CONFIG_FILE: https://github.com/timwebster9/jenkins-config-home.git
  JAVA_OPTS: >
    -Djenkins.install.runSetupWizard=false
    -Dhudson.slaves.NodeProvisioner.initialDelay=0
    -Dhudson.slaves.NodeProvisioner.MARGIN=50
    -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildit-jenkins
  namespace: buildit-jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: builditdigital/jenkins-image:2.6.0-alpine
        name: jenkins
        env:
        - name: JENKINS_CONFIG_FILE
          valueFrom:
            configMapKeyRef:
              name: buildit-jenkins-config
              key: JENKINS_CONFIG_FILE
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: buildit-jenkins-config
              key: JAVA_OPTS
        # Need to create namespace first
        # Secret created manually: https://kubernetes.io/docs/concepts/configuration/secret/#creating-your-own-secrets
        # e.g. kubectl create secret generic jenkins-startup-secret --from-literal=JENKINS_STARTUP_SECRET=<secret> -n buildit-jenkins
        - name: JENKINS_STARTUP_SECRET
          valueFrom:
            secretKeyRef:
              name: jenkins-startup-secret
              key: JENKINS_STARTUP_SECRET
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: buildit-encryptor
  namespace: buildit-jenkins
spec:
  ports:
  - name: ui
    protocol: TCP
    port: 80
    targetPort: 4567
  selector:
    app: encryptor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildit-encryptor
  namespace: buildit-jenkins
spec:
  selector:
    matchLabels:
      app: encryptor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: encryptor
    spec:
      containers:
      - image: builditdigital/encryptor-api:2.4.0
        name: encryptor
        ports:
        - containerPort: 4567
          name: http
---
# Follow this to install nginx ingress controller: https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/installation.md
# For bare-metal I would recommend a daemon-set, which will run nginx on all nodes and expose ports 80/443 on them (or use nginx-ingress-daemonset.yaml)
# For cloud you can use a service of type 'LoadBalancer'
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: buildit-jenkins-ingress
  namespace: buildit-jenkins
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  # Your DNS has to be able to resolve this hostname
  - host: buildit-jenkins.portworx.zone
    http:
      paths:
      - backend: 
          serviceName: buildit-jenkins
          servicePort: 80
  - host: jenkins.deggymacets.com
    http:
      paths:
      - backend: 
          serviceName: buildit-jenkins
          servicePort: 80
  - host: buildit-encryptor.portworx.zone
    http:
      paths:
      - backend: 
          serviceName: buildit-encryptor
          servicePort: 80

