kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: buildit-jenkins
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions"]
  resources: ["deployments", "replicasets", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: buildit-jenkins
subjects:
- kind: ServiceAccount
  name: default
  namespace: buildit-jenkins
roleRef:
  kind: ClusterRole
  name: buildit-jenkins 
  apiGroup: rbac.authorization.k8s.io
---